//GENERATED. DO NOT MODIFY DIRECTLY!
//This module exports all builtin "binder" templates
//It is created by processing binders.lodash with the output of the hulk CLI
var Hogan = require('hogan.js');
/* jshint ignore:start */
if (!!!templates) var templates = {};
templates["amd"] = new Hogan.Template({code: function (c,p,i) { var t=this;t.b(i=i||"");t.b("define(['hogan'], function(Hogan) {");t.b("\n" + i);t.b("  var t = {");t.b("\n" + i);t.b("    /* jshint ignore:start */");t.b("\n" + i);if(t.s(t.f("templates",c,p,1),c,p,0,159,225,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("    '");t.b(t.v(t.f("name",c,p,0)));t.b("' : new Hogan.Template(");t.b(t.t(t.f("template",c,p,0)));t.b(")");t.b(t.v(t.f("comma",c,p,0)));t.b("\n" + i);});c.pop();}t.b("    /* jshint ignore:end */");t.b("\n" + i);t.b("  },");t.b("\n" + i);t.b("  r = function(n) {");t.b("\n" + i);t.b("    var tn = t[n];");t.b("\n" + i);t.b("    return function(c, p, i) {");t.b("\n" + i);t.b("      return tn.render(c, p || t, i);");t.b("\n" + i);t.b("    };");t.b("\n" + i);t.b("  };");t.b("\n" + i);t.b("  return {");t.b("\n" + i);if(t.s(t.f("exposeTemplates",c,p,1),c,p,0,428,452,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("    templates : t,");t.b("\n" + i);});c.pop();}if(t.s(t.f("templates",c,p,1),c,p,0,490,535,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("    '");t.b(t.v(t.f("name",c,p,0)));t.b("' : r('");t.b(t.v(t.f("name",c,p,0)));t.b("')");t.b(t.v(t.f("comma",c,p,0)));t.b("\n" + i);});c.pop();}t.b("  };");t.b("\n" + i);t.b("});");return t.fl(); },partials: {}, subs: {  }});
templates["bootstrap"] = new Hogan.Template({code: function (c,p,i) { var t=this;t.b(i=i||"");t.b("var Hogan = require('hogan.js');");t.b("\n" + i);t.b("var templates = {};");t.b("\n" + i);t.b("/* jshint ignore:start */");t.b("\n" + i);if(t.s(t.f("templates",c,p,1),c,p,0,141,203,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("templates['");t.b(t.v(t.f("name",c,p,0)));t.b("'] = new Hogan.Template(");t.b(t.t(t.f("template",c,p,0)));t.b("); ");t.b("\n" + i);});c.pop();}t.b("/* jshint ignore:end */");t.b("\n" + i);t.b("module.exports = templates;");return t.fl(); },partials: {}, subs: {  }});
templates["default"] = new Hogan.Template({code: function (c,p,i) { var t=this;t.b(i=i||"");t.b("(function (exports) {");t.b("\n" + i);t.b("  var Hogan = require('hogan.js');");t.b("\n" + i);t.b("  ");t.b("\n" + i);t.b("  var t = {");t.b("\n" + i);t.b("    /* jshint ignore:start */");t.b("\n" + i);if(t.s(t.f("templates",c,p,1),c,p,0,180,246,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("    '");t.b(t.v(t.f("name",c,p,0)));t.b("' : new Hogan.Template(");t.b(t.t(t.f("template",c,p,0)));t.b(")");t.b(t.v(t.f("comma",c,p,0)));t.b("\n" + i);});c.pop();}t.b("    /* jshint ignore:end */");t.b("\n" + i);t.b("  },");t.b("\n" + i);t.b("  r = function(n) {");t.b("\n" + i);t.b("    var tn = t[n];");t.b("\n" + i);t.b("    return function(c, p, i) {");t.b("\n" + i);t.b("      return tn.render(c, p || t, i);");t.b("\n" + i);t.b("    };");t.b("\n" + i);t.b("  };");t.b("\n" + i);t.b("  return {");t.b("\n" + i);if(t.s(t.f("exposeTemplates",c,p,1),c,p,0,449,473,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("    templates : t,");t.b("\n" + i);});c.pop();}if(t.s(t.f("templates",c,p,1),c,p,0,512,557,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("    '");t.b(t.v(t.f("name",c,p,0)));t.b("' : r('");t.b(t.v(t.f("name",c,p,0)));t.b("')");t.b(t.v(t.f("comma",c,p,0)));t.b("\n" + i);});c.pop();}t.b("  };");t.b("\n" + i);t.b("}(typeof exports === 'undefined' ? (this.");t.b(t.v(t.f("exportName",c,p,0)));t.b(" = {}) : exports));");return t.fl(); },partials: {}, subs: {  }});
templates["hulk"] = new Hogan.Template({code: function (c,p,i) { var t=this;t.b(i=i||"");t.b("var templates = {};\r");t.b("\n" + i);t.b("/* global Hogan */\r");t.b("\n" + i);t.b("/* jshint ignore:start */\r");t.b("\n" + i);if(t.s(t.f("templates",c,p,1),c,p,0,160,223,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("templates['");t.b(t.v(t.f("name",c,p,0)));t.b("'] = new Hogan.Template(");t.b(t.t(t.f("template",c,p,0)));t.b(");\r");t.b("\n" + i);});c.pop();}t.b("/* jshint ignore:end */");return t.fl(); },partials: {}, subs: {  }});
templates["nodejs"] = new Hogan.Template({code: function (c,p,i) { var t=this;t.b(i=i||"");t.b("var Hogan = require('hogan.js');");t.b("\n");t.b("\n" + i);t.b("var t = {");t.b("\n" + i);t.b("  /* jshint ignore:start */");t.b("\n" + i);if(t.s(t.f("templates",c,p,1),c,p,0,140,202,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("  '");t.b(t.v(t.f("name",c,p,0)));t.b("' : new Hogan.Template(");t.b(t.t(t.f("template",c,p,0)));t.b(")");t.b(t.v(t.f("comma",c,p,0)));t.b("\n" + i);});c.pop();}t.b("  /* jshint ignore:end */");t.b("\n" + i);t.b("},");t.b("\n" + i);t.b("r = function(n) {");t.b("\n" + i);t.b("  var tn = t[n];");t.b("\n" + i);t.b("  return function(c, p, i) {");t.b("\n" + i);t.b("    return tn.render(c, p || t, i);");t.b("\n" + i);t.b("  };");t.b("\n" + i);t.b("};");t.b("\n" + i);t.b("module.exports = {");t.b("\n" + i);if(t.s(t.f("exposeTemplates",c,p,1),c,p,0,395,415,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("  templates : t,");t.b("\n" + i);});c.pop();}if(t.s(t.f("templates",c,p,1),c,p,0,452,493,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("  '");t.b(t.v(t.f("name",c,p,0)));t.b("' : r('");t.b(t.v(t.f("name",c,p,0)));t.b("')");t.b(t.v(t.f("comma",c,p,0)));t.b("\n" + i);});c.pop();}t.b("};");return t.fl(); },partials: {}, subs: {  }});
templates["revealing"] = new Hogan.Template({code: function (c,p,i) { var t=this;t.b(i=i||"");t.b("/* global Hogan */");t.b("\n" + i);t.b("var ");t.b(t.v(t.f("exportName",c,p,0)));t.b(" = (function() {");t.b("\n" + i);t.b("  ");t.b("\n" + i);t.b("var t = {");t.b("\n" + i);t.b("  /* jshint ignore:start */");t.b("\n" + i);if(t.s(t.f("templates",c,p,1),c,p,0,171,233,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("  '");t.b(t.v(t.f("name",c,p,0)));t.b("' : new Hogan.Template(");t.b(t.t(t.f("template",c,p,0)));t.b(")");t.b(t.v(t.f("comma",c,p,0)));t.b("\n" + i);});c.pop();}t.b("  /* jshint ignore:end */");t.b("\n" + i);t.b("},");t.b("\n" + i);t.b("r = function(n) {");t.b("\n" + i);t.b("  var tn = t[n];");t.b("\n" + i);t.b("  return function(c, p, i) {");t.b("\n" + i);t.b("    return tn.render(c, p || t, i);");t.b("\n" + i);t.b("  };");t.b("\n" + i);t.b("};");t.b("\n" + i);t.b("return {");t.b("\n" + i);if(t.s(t.f("exposeTemplates",c,p,1),c,p,0,416,436,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("  templates : t,");t.b("\n" + i);});c.pop();}if(t.s(t.f("templates",c,p,1),c,p,0,473,514,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("  '");t.b(t.v(t.f("name",c,p,0)));t.b("' : r('");t.b(t.v(t.f("name",c,p,0)));t.b("')");t.b(t.v(t.f("comma",c,p,0)));t.b("\n" + i);});c.pop();}t.b("};");t.b("\n" + i);t.b("})();");return t.fl(); },partials: {}, subs: {  }});

module.exports = templates;
/* jshint ignore:end */